project:
  type: website
  output-dir: docs

website:
  title: "quarto-experiments"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about
      - href: 030_quarto_katex_html_references.qmd
        text: katex
      - href: 001_tech_reading.qmd
        text: tech_reading
      - href: 01030_poisson_distribution.qmd
        text: 01030_poisson_distribution.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



