project:
  type: website
  output-dir: docs

website:
  title: "quarto-experiments"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about
      - href: 030_quarto_katex_html_references.qmd
        text: katex
      - href: 001_tech_reading.qmd
        text: tech_reading
      - href: 01030_poisson_distribution.qmd
        text: 01030_poisson_distribution.qmd
      - href: not_zero.qmd
        text: not zero
      - href: 010_mtcars_basic.qmd
        text: Where does mtcars live?
      - href: 020_CSS_play.qmd
        text: 020 CSS play
      - href: 400_rlang_proposal.qmd
        text: Rlang Guide?
      - href: 310_R_notes.qmd
        text: R_notes (DRAFT)
      - href: 410_bquote_example.qmd
        text: bquote_examples
        

format:
  html:
    theme: cosmo
    css: css_examples.css
    toc: true



